services:
  postgres:
    image: postgres:15
    container_name: spark_etl_pg
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spark_net

  spark:
    build: .
    container_name: spark_etl_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # postgres
      DB_HOST: postgres
      DB_PORT: 5432
      # minio (из parquet-iceberg-s3)
      S3_ENDPOINT: http://host.docker.internal:9000
    volumes:
      - ./main.py:/app/main.py
      - ./python_etl.py:/app/python_etl.py
      - ./config.py:/app/config.py
    networks:
      - spark_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["sleep", "infinity"]

volumes:
  pgdata:

networks:
  spark_net:
    driver: bridge
